export interface Anime {
  id: string;
  title: string;
  image: string;
  backdropImage?: string;
  description: string;
  rating: number;
  year: number;
  episodes?: number;
  type: "movie" | "series";
  genres: string[];
  duration?: string;
  status?: string;
}

export const trendingAnime: Anime[] = [
  {
    id: "1",
    title: "Demon Slayer: Kimetsu no Yaiba",
    image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=600&fit=crop",
    description: "A young boy becomes a demon slayer after his family is slaughtered.",
    rating: 9.2,
    year: 2019,
    episodes: 44,
    type: "series",
    genres: ["Action", "Fantasy"],
  },
  {
    id: "2",
    title: "Attack on Titan",
    image: "https://images.unsplash.com/photo-1541562232579-512a21360571?w=400&h=600&fit=crop",
    description: "Humanity fights for survival against giant humanoid Titans.",
    rating: 9.5,
    year: 2013,
    episodes: 87,
    type: "series",
    genres: ["Action", "Drama"],
  },
  {
    id: "3",
    title: "Jujutsu Kaisen",
    image: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400&h=600&fit=crop",
    description: "A boy swallows a cursed talisman and becomes host to an evil spirit.",
    rating: 8.9,
    year: 2020,
    episodes: 47,
    type: "series",
    genres: ["Action", "Supernatural"],
  },
  {
    id: "4",
    title: "Spy x Family",
    image: "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?w=400&h=600&fit=crop",
    description: "A spy must build a fake family to execute a mission.",
    rating: 8.7,
    year: 2022,
    episodes: 25,
    type: "series",
    genres: ["Action", "Comedy"],
  },
  {
    id: "5",
    title: "Chainsaw Man",
    image: "https://images.unsplash.com/photo-1560972550-aba3456b5564?w=400&h=600&fit=crop",
    description: "A young man merges with his pet devil to become Chainsaw Man.",
    rating: 8.8,
    year: 2022,
    episodes: 12,
    type: "series",
    genres: ["Action", "Horror"],
  },
  {
    id: "6",
    title: "One Punch Man",
    image: "https://images.unsplash.com/photo-1535016120720-40c646be5580?w=400&h=600&fit=crop",
    description: "A hero who can defeat any opponent with a single punch seeks excitement.",
    rating: 8.7,
    year: 2015,
    episodes: 24,
    type: "series",
    genres: ["Action", "Comedy"],
  },
];

export const popularAnime: Anime[] = [
  {
    id: "7",
    title: "My Hero Academia",
    image: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&h=600&fit=crop",
    description: "In a world of superpowers, a powerless boy dreams of becoming a hero.",
    rating: 8.4,
    year: 2016,
    episodes: 138,
    type: "series",
    genres: ["Action", "School"],
  },
  {
    id: "8",
    title: "One Piece",
    image: "https://images.unsplash.com/photo-1601850494422-3cf14624b0b3?w=400&h=600&fit=crop",
    description: "A young pirate searches for the ultimate treasure, the One Piece.",
    rating: 9.0,
    year: 1999,
    episodes: 1100,
    type: "series",
    genres: ["Adventure", "Action"],
  },
  {
    id: "9",
    title: "Naruto Shippuden",
    image: "https://images.unsplash.com/photo-1614583225154-5fcdda07019e?w=400&h=600&fit=crop",
    description: "Naruto continues his quest to become Hokage and save his friend.",
    rating: 8.8,
    year: 2007,
    episodes: 500,
    type: "series",
    genres: ["Action", "Adventure"],
  },
  {
    id: "10",
    title: "Death Note",
    image: "https://images.unsplash.com/photo-1606663889134-b1dedb5ed8b7?w=400&h=600&fit=crop",
    description: "A genius student uses a supernatural notebook to eliminate criminals.",
    rating: 9.0,
    year: 2006,
    episodes: 37,
    type: "series",
    genres: ["Thriller", "Supernatural"],
  },
  {
    id: "11",
    title: "Fullmetal Alchemist",
    image: "https://images.unsplash.com/photo-1580477667995-2b94f01c9516?w=400&h=600&fit=crop",
    description: "Two brothers use alchemy to search for the Philosopher's Stone.",
    rating: 9.1,
    year: 2009,
    episodes: 64,
    type: "series",
    genres: ["Action", "Adventure"],
  },
  {
    id: "12",
    title: "Tokyo Ghoul",
    image: "https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=400&h=600&fit=crop",
    description: "A college student becomes half-ghoul after a deadly encounter.",
    rating: 8.0,
    year: 2014,
    episodes: 48,
    type: "series",
    genres: ["Horror", "Action"],
  },
];

export const newReleases: Anime[] = [
  {
    id: "13",
    title: "Solo Leveling",
    image: "https://images.unsplash.com/photo-1559583109-3e7968136c99?w=400&h=600&fit=crop",
    description: "The weakest hunter becomes the strongest through a mysterious system.",
    rating: 9.1,
    year: 2024,
    episodes: 12,
    type: "series",
    genres: ["Action", "Fantasy"],
  },
  {
    id: "14",
    title: "Frieren: Beyond Journey's End",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop",
    description: "An elf mage reflects on her journey after her party defeats the Demon King.",
    rating: 9.3,
    year: 2023,
    episodes: 28,
    type: "series",
    genres: ["Adventure", "Fantasy"],
  },
  {
    id: "15",
    title: "Blue Lock",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop",
    description: "Japan creates a program to develop the world's greatest striker.",
    rating: 8.5,
    year: 2022,
    episodes: 24,
    type: "series",
    genres: ["Sports", "Drama"],
  },
  {
    id: "16",
    title: "Oshi no Ko",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=600&fit=crop",
    description: "A doctor is reborn as the child of his favorite idol.",
    rating: 8.9,
    year: 2023,
    episodes: 11,
    type: "series",
    genres: ["Drama", "Supernatural"],
  },
  {
    id: "17",
    title: "Vinland Saga",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=400&h=600&fit=crop",
    description: "A young Viking seeks revenge against his father's killer.",
    rating: 9.0,
    year: 2019,
    episodes: 48,
    type: "series",
    genres: ["Action", "Historical"],
  },
  {
    id: "18",
    title: "Hell's Paradise",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    description: "A ninja on death row must find the elixir of immortality.",
    rating: 8.3,
    year: 2023,
    episodes: 13,
    type: "series",
    genres: ["Action", "Supernatural"],
  },
];

export const animeMovies: Anime[] = [
  {
    id: "19",
    title: "Your Name",
    image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop",
    description: "Two teenagers discover they are magically swapping bodies.",
    rating: 9.4,
    year: 2016,
    type: "movie",
    genres: ["Romance", "Fantasy"],
    duration: "1h 46m",
  },
  {
    id: "20",
    title: "Spirited Away",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop",
    description: "A girl enters a world of spirits to save her parents.",
    rating: 9.3,
    year: 2001,
    type: "movie",
    genres: ["Fantasy", "Adventure"],
    duration: "2h 5m",
  },
  {
    id: "21",
    title: "Weathering With You",
    image: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=400&h=600&fit=crop",
    description: "A boy meets a girl who can manipulate the weather.",
    rating: 8.4,
    year: 2019,
    type: "movie",
    genres: ["Romance", "Fantasy"],
    duration: "1h 52m",
  },
  {
    id: "22",
    title: "A Silent Voice",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
    description: "A former bully seeks redemption by reconnecting with his victim.",
    rating: 9.0,
    year: 2016,
    type: "movie",
    genres: ["Drama", "Romance"],
    duration: "2h 10m",
  },
  {
    id: "23",
    title: "Princess Mononoke",
    image: "https://images.unsplash.com/photo-1518173946687-a4c036bc613e?w=400&h=600&fit=crop",
    description: "A prince becomes involved in a struggle between nature and industry.",
    rating: 9.1,
    year: 1997,
    type: "movie",
    genres: ["Fantasy", "Adventure"],
    duration: "2h 14m",
  },
  {
    id: "24",
    title: "Suzume",
    image: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop",
    description: "A girl must close doors causing disasters across Japan.",
    rating: 8.6,
    year: 2022,
    type: "movie",
    genres: ["Fantasy", "Adventure"],
    duration: "2h 2m",
  },
];

export const genres = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Fantasy",
  "Horror",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
];

export const allAnime = [
  ...trendingAnime,
  ...popularAnime,
  ...newReleases,
  ...animeMovies,
];
